# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "11th Annual Vapicon 2019 Yavatmal"
email: "vapicon2019@gmail.con"
description: "Annual Conference of The Asssociation Of Physicians of India Vidarbha Chapter"
baseurl: ""
url: "https://vapicon.org"
permalink: "/news/:title"
googleAnalyticsTrackingId: "UA-129016127-1"
googleAnalyticsSiteUrl: "vapicon.org"
siteVerification: "AIzaSyDWkde1vX5nn5w07ytfb97Wq4CvPZy62Sg"

# Organizer Info
organizerName: "API Yavatmal and VNGMC  Yavatmal"
organizerAlternateName: "API Yavatmal"
organizerDescription: "We share the advancements in medical science which will be highly useful for medical practitioners"
organizerEmail: "vapicon2019@gmail.com"
organizerLogo: "/img/seo/api.png"


# Head
metaKeywords: "vapicon,yavatmal"
twitterAccount: "@Vapicon"




# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/news/", text: "News"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Poster and Paper Presentation"}


# Hero Block
heroImage: "heart3.jpg"
heroTitle: "Vapicon <typeout> 2019"
eventDate: "January 12th-13th, 2019"
typeoutTextValues: '"", "Season", "Yavatmal"'
typeoutFallback: "Season"

# About Block
aboutTitle: "About Vapicon"
aboutBlock:
 - {title: "Lectures", image: "rajkumarmani.jpg", text: "11th Annual conference of Vidharbha Asssociation of Physicians 2019" }
 - {title: "Poster Presentation", image: "workshop.jpg", text: "Present your research papers at the conference." }
 

# Statistic Block
statisticBlockImage: "images.jpeg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "18", specialCharacter: "+", info: "hours", detail: "of medical advancements"}
 - {count: "30", specialCharacter: "+", info: "speakers", detail: "from all over the country"}
 

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Jawharlala Darda Shrotru Gruha"
eventStreetAddress: "Shri. VASANTRAO NAIK MEDICAL COLLEGE"
eventAddressLocality: "Waghapur Road, Palswadi Camp, Civil Lines"
eventAddressLocalityRegion: "Yavatmal"
eventPostalCode: "445001"
eventAddressCountry: "India"
eventStartTime: "2019-01-12T09:30"
eventDoorTime: "09:00"
eventEndTime: "2019-01-13T20:00"
eventPlaceCoordinateLat: 20.3961
eventPlaceCoordinateLng: 78.1193

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "1.jpg"
venueSmallImage1: "aven.jpg"
venueSmallImage2: "2.jpg"
venueSmallImage3: "aven.jpg"
venueTitle: "Jawharlala Darda Shrotru Gruha"
venueFeatures: ["Shri.VASANTRAO NAIK MEDICAL COLLEGE"]

# Tweets Feed Block
tweetsFeedImage: "yvt.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "Vapicon"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"

# Tickets Block
ticketsTitle: "Registration Fees"
ticketsInfo: "Registration Fees grant access to all conference sections, breakfast, lunch and banquet.<br>Student have to bring letter from Head of Deapartment of concerned institution.<br>For complimentary accomodation please Call:Dr. Sandeep Dhawane - 9763421633 OR Mr. Raju Andulkar - 9822717917"
ticketsOffers:
 -
  name: "Early Bird"
  price: "4000"
  priceCurrency: "Rupees"
  ticketContentList: ["Valid for all lectures", "Refreshments", "Banquet"]
  validFrom: "2018-11-20T10:00"
  validThrough: "2018-12-31T23:59"
  featured: true
 -
  name: "Regular"
  price: "5000"
  priceCurrency: "Rupees"
  featured: true
  ticketContentList: ["Valid for all lectures", "Refreshments", "Banquet"]
  validFrom: "2019-01-01T00:00"
  validThrough: "2019-01-11T23:59"
 -
  name: "Spot"
  price: "6000"
  priceCurrency: "Rupees"
  ticketContentList: ["Valid for all lectures", "Refreshments", "Banquet"]
  validFrom: "2019-01-12T10:00"
  validThrough: "2019-01-13T23:59"
  featured: true
 -
  name: "Students"
  price: "1500"
  priceCurrency: "Rupees"
  ticketContentList: ["Valid for all lectures", "Refreshments", "Banquet"]
  validFrom: "2018-11-20T10:00"
  validThrough: "2019-01-13T23:59"
  featured: true

# Footer

footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:vapicon2019@gmail.com", text: "vapicon2019@gmail.com"}
 

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "vapicon"

# Speakers List Block
showSessions: true





# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "20.3961, 78.1193"
logisticsMapMobileCenterCoordinates: "20.3961, 78.1193"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Yavatmal"
directionDetailsCards:

 - {title: "Public Transit", information: 'Google Transit is available in Yavatmal. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Yavatmal.'}
 - {title: "Hotels", information: 'Yavatmal has lots of great hotels and hostels. More information will be available later.'}
 - {title: "Places to visit nearby", information: '1)Tipeshwar Wildlife Sanctuary<br>2)Chintamani Ganpati Mandir<br>3)Mahadev Temple<br>4)The Renuka Devi Temple as a Shakti Peeth(Mahur)<br>5)Tadoba National Park'}

# Hackathon
hackathonTitle: "Poster and Paper Presentation"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Poster Presentation Prize"
hackathonRows:
 - {title: "2000 Rupees", image: "first.png", details: "First Place"}
 - {title: "1500 Rupees", image: "second.png", details: "Second Place"}
 - {title: "1000 Rupees", image: "third.png", details: "Third Place"}

# Hackathon Judges Block
judgesImage: "judge.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Mrs. Asha Ashok Wasalwar best paper award"
prizes:
 - {title: "2000 Rupees", image: "second.png", info: "Second Place"}
 - {title: "3000 Rupees", image: "first.png", info: "First Place"}
 - {title: "1000 Rupees", image: "third.png", info: "Third Place"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Jawharlala Darda Shrotru Gruha"
hackathonStreetAddress: "Waghapur Road, Palswadi Camp, Civil Lines"
hackathonAddressLocality: "Yavatmal"
hackathonAddressLocalityRegion: "Yavatmal"
hackathonPostalCode: "445001"
hackathonAddressCountry: "India"
hackathonTimeTitle: "Present At"
hackathonStartTime: "2019-01-12T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2019-01-13T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "20.3961, 78.1193"
hackathonMapCenterCoordinates: "20.3961, 78.1193"
hackathonMapMobileCenterCoordinates: "20.3961, 78.1193"
